module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "primary": "#006c75",
              "background-light": "#f5f8f8",
              "background-dark": "#0f2223",
              "secondary-container": "#cde7eb",
              "on-surface": "#171c1d",
              "tertiary": "#6e5d2e",
              "surface-variant": "#dae4e5",
              "on-background": "#171c1d",
              "tertiary-container": "#f8e1a7",
              "on-secondary-fixed": "#091f22",
              "on-tertiary": "#ffffff",
              "tertiary-fixed": "#f8e1a7",
              "on-primary-fixed-variant": "#004f56",
              "on-secondary": "#ffffff",
              "on-surface-variant": "#3f484a",
              "tertiary-fixed-dim": "#dbc58d",
              "on-secondary-fixed-variant": "#354a4e",
              "primary-fixed-dim": "#82d3de",
              "on-tertiary-fixed-variant": "#544519",
              "surface-container-lowest": "#ffffff",
              "surface-container": "#eceef0",
              "on-primary": "#ffffff",
              "error-container": "#ffdad6",
              "inverse-surface": "#2c3132",
              "surface": "#f8fafa",
              "surface-dim": "#d6dbdb",
              "on-error": "#ffffff",
              "on-primary-container": "#ffffff",
              "surface-tint": "#006971",
              "surface-container-high": "#e6e9e9",
              "secondary-fixed-dim": "#b3cbcf",
              "background": "#f8fafa",
              "inverse-on-surface": "#eff1f1",
              "error": "#ba1a1a",
              "secondary": "#4d6266",
              "on-secondary-container": "#354a4e",
              "outline": "#70797b",
              "surface-bright": "#f8fafa",
              "inverse-primary": "#82d3de",
              "outline-variant": "#bfc8ca",
              "on-error-container": "#410002",
              "primary-container": "#005259",
              "primary-fixed": "#9ff0fb",
              "secondary-fixed": "#cfe7ec",
              "on-primary-fixed": "#001f22",
              "on-tertiary-fixed": "#241a00",
              "surface-container-highest": "#e0e3e3",
              "surface-container-low": "#f2f4f4",
              "on-tertiary-container": "#241a00"
          },
          fontFamily: {
              "display": ["Inter", "sans-serif"]
          },
          borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
      },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
